apiVersion: v1
kind: Pod
metadata:
  name: my-app-signed-pod
spec:
  containers:
  - name: my-app-signed
    image: harbor.harbor.svc.cluster.local/library/my-app-signed:latest
  imagePullSecrets:
  - name: harbor-creds
