apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
  - name: my-app
    image: harbor.harbor.svc.cluster.local/library/my-image:latest
    ports:
    - containerPort: 80 # Falls deine App auf einem Port lauscht
  imagePullSecrets:
  - name: harbor-pull-secret
