apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-app-backend
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: projects
      version: v2
      auth:
        tokenSecretRef:
          name: eso-vault-token
          namespace: crossplane-system
          key: token
