apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: compositeappsecretimports.idp.demo.io
spec:
  scope: Namespaced
  group: idp.demo.io
  names:
    kind: CompositeAppSecretImport
    plural: compositeappsecretimports
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - appName
                - importName
                - source
                - bindAs
              properties:
                appName:
                  type: string
                importName:
                  type: string
                namespace:
                  type: string
                source:
                  type: object
                  required:
                    - vault
                  properties:
                    vault:
                      type: object
                      required:
                        - path
                      properties:
                        path:
                          type: string
                        secretStoreRef:
                          type: string
                        fieldMap:
                          type: object
                          additionalProperties:
                            type: string
                bindAs:
                  type: object
                  properties:
                    secretName:
                      type: string
                    usernamePassword:
                      type: object
                      properties:
                        envVars:
                          type: object
                          required:
                            - username
                            - password
                          properties:
                            username:
                              type: string
                            password:
                              type: string
            status:
              type: object
              properties:
                phase:
                  type: string
