apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "unified-application.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.containerPort }}
