# the same credentials as for postgres cluster creation
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
stringData:
  POSTGRES_USER: backstage_user
  POSTGRES_PASSWORD: your_secure_password
  POSTGRES_HOST: backstage-db-rw.backstage.svc.cluster.local
  POSTGRES_PORT: "5432"
---
# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: backstage:latest
          imagePullPolicy: Never  # we want to use the image loaded into kind
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http
