apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-db-auth
  namespace: backstage
type: kubernetes.io/basic-auth
stringData:
  username: backstage_user
  password: your_secure_password
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-db
  namespace: backstage
spec:
  instances: 3
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: postgres
      owner: backstage_user
      secret:
        name: backstage-db-auth
      # FIXME: Does not work
      postInitApplicationSQL:
        - "ALTER USER backstage_user WITH CREATEDB;"
