apiVersion: v1
kind: Secret
metadata:
  name: vault-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: '{"token": "root"}'
---
apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  address: http://vault.vault.svc.cluster.local:8200
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: vault-creds
      key: credentials
