apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  name: kv-v2-engine
spec:
  forProvider:
    path: "example-engine"
    type: "kv-v2"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-payload-json
  namespace: crossplane-system
type: Opaque
stringData:
  json: '{"username":"admin","password":"very-secure-password"}'
---
apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
metadata:
  name: db-credentials
spec:
  forProvider:
    name: "database/config"
    mount: "example-engine"
    dataJsonSecretRef:
      name: db-payload-json
      namespace: crossplane-system
      key: json
