apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-razorapps-providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/rklonner/cloud-native-labs.git
    targetRevision: HEAD
    path: crossplane/composition-app-with-database-and-vault-integration-argocd/argocd/resources/providers
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
