apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-razorapps-workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/rklonner/cloud-native-labs.git
    targetRevision: HEAD
    path: crossplane/composition-app-with-database-and-vault-integration-argocd/argocd/resources/workloads
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
