apiVersion: v1
kind: Namespace
metadata:
  name: aurora
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aurora-sa
  namespace: razor
---
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: aurora-policy
spec:
  forProvider:
    name: "aurora-policy"
    policy: |
      path "projects/data/aurora/*" {
        capabilities = ["read", "list"]
      }
---
apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: aurora-role
spec:
  forProvider:
    # Verweist auf das Auth-Backend (standardmäßig "kubernetes")
    backend: "kubernetes"
    roleName: "aurora-role"
    boundServiceAccountNames:
      - "aurora-sa"
    boundServiceAccountNamespaces:
      - "aurora"
    tokenPolicies:
      - "aurora-policy" # Muss exakt dem 'name' in der Policy oben entsprechen
    tokenTtl: 3600
---
apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: aurora-db
spec:
  providerConfigRef:
    name: mssql-local
  writeConnectionSecretToRef:
    name: secret-aurora-db-conn # Nur noch lokales K8s-Secret
    namespace: crossplane-system
---
# RO User
apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: User
metadata:
  name: aurora-readonly-user
spec:
  forProvider:
    database: aurora-db      # Target your database
  writeConnectionSecretToRef:
    name: secret-aurora-db-readonly-user
    namespace: crossplane-system
  providerConfigRef:
    name: mssql-local
---
# RW User
apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: User
metadata:
  name: aurora-readwrite-user
spec:
  forProvider:
    database: aurora-db      # Target your database
  writeConnectionSecretToRef:
    name: secret-aurora-db-readwrite-user
    namespace: crossplane-system
  providerConfigRef:
    name: mssql-local  
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-aurora-db-ro-user-to-vault
  namespace: crossplane-system
spec:
  # secret store points to secret engine "projects" in vault
  secretStoreRefs:
    - name: eso-secret-store-vault-backend # Dein neuer funktionierender Store
      kind: SecretStore
  selector:
    secret:
      name: secret-aurora-db-readonly-user # Quelle von Crossplane
  data:
    - match:
        secretKey: # if emtpy, all secret attributes will be pushed
        remoteRef:
          remoteKey: aurora/database/ro-user
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-aurora-db-rw-user-to-vault
  namespace: crossplane-system
spec:
  # secret store points to secret engine "projects" in vault
  secretStoreRefs:
    - name: eso-secret-store-vault-backend # Dein neuer funktionierender Store
      kind: SecretStore
  selector:
    secret:
      name: secret-aurora-db-readwrite-user # Quelle von Crossplane
  data:
    - match:
        secretKey: # if emtpy, all secret attributes will be pushed
        remoteRef:
          remoteKey: aurora/database/rw-user