apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-run-
spec:
  entrypoint: call-template
  serviceAccountName: default
  
  # workflow template expects a PVC named 'workdir' to share data between steps
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  arguments:
    parameters:
    - name: repo-url
      value: "https://github.com/dag-andersen/argocd-diff-preview.git"
    - name: dockerfile
      value: "Dockerfile"
    - name: image-name
      value: "my-app:v1"

  templates:
  - name: call-template
    steps:
    - - name: run-build
        templateRef:
          name: buildah-git-template
          template: main

