apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-clone-build-push-sign-harbor-harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.18.0
    helm:
      values: |
        expose:
          type: clusterIP
          tls:
            enabled: true
            auto:
              commonName: harbor.harbor.svc.cluster.local
        externalURL: https://harbor.harbor.svc.cluster.local
        persistence:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
