apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/rklonner/cloud-native-labs.git
    targetRevision: HEAD
    path: argo-workflows/clone-build-push-sign-harbor/apps/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
