apiVersion: v1
kind: Secret
metadata:
  name: harbor-creds
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.harbor.svc.cluster.local": {
          "username": "admin",
          "password": "Harbor12345",
          "auth": "YWRtaW46SGFyYm9yMTIzNDU="
        }
      }
    }
