apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  admin.password: "$2a$10$vM1hppCxsg.dh0j2/NSwY.qFyXZe2I40L1ZAAU19cejKJCuiJ7l5G"
  admin.passwordMtime: "2026-07-14T20:36:42Z"
