apiVersion: v1
kind: Service
metadata:
  name: argocd-server-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32080
