apiVersion: v1
kind: Service
metadata:
  name: harbor-local
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort
  selector:
    app: harbor
    component: nginx
    release: lab-clone-build-push-sign-harbor-harbor
  ports:
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 32443
