apiVersion: v1
kind: Namespace
metadata:
  name: blade
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: aurora
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
